import type { Metadata } from 'next';
import Link from 'next/link';
import { unstable_setRequestLocale } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Terms of Use | MarkM8',
  description: 'Terms of Use for MarkM8\'s AI-powered essay grading platform. Learn about your rights and responsibilities when using our educational services.',
};

export default async function TermsOfService(props: { params: Promise<{ locale: string }> }) {
  const { locale } = await props.params;
  unstable_setRequestLocale(locale);

  const lastUpdated = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  return (
    <div className="min-h-screen bg-gradient-to-br from-violet-50 via-white to-violet-50">
      <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
        <div className="rounded-lg bg-white p-8 shadow-lg md:p-12">
          <h1 className="mb-2 text-4xl font-bold text-slate-900">MarkM8 Terms of Use</h1>
          <p className="mb-8 text-sm text-slate-600">
            Last Updated:
            {' '}
            {lastUpdated}
          </p>

          <div className="prose prose-slate max-w-none">
            {/* 1. Introduction */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">1. Introduction</h2>
              <p className="mb-4 text-slate-700">
                Welcome to MarkM8 (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;). MarkM8 is an AI-powered educational support platform designed to help users improve their academic writing through feedback and guidance. By accessing or using our website and services (&quot;Platform&quot;), you agree to comply with and be bound by these Terms of Use (&quot;Terms&quot;). Please read them carefully before using MarkM8.
              </p>
              <div className="rounded-lg border border-red-200 bg-red-50 p-4">
                <p className="font-medium text-red-800">
                  If you do not agree to these Terms, do not use our Platform.
                </p>
              </div>
            </section>

            {/* 2. Eligibility and User Accounts */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">2. Eligibility and User Accounts</h2>
              <ul className="list-disc space-y-2 pl-6 text-slate-700">
                <li>You must be at least 16 years old to use our Platform. If you are under 18, you confirm you have the consent of a parent or legal guardian.</li>
                <li>Users must ensure the security of their account credentials and are responsible for all activity under their account.</li>
                <li>We may suspend or terminate accounts in the event of breach of these Terms.</li>
                <li>We may restrict access or eligibility based on age, jurisdiction, or other criteria at our discretion.</li>
              </ul>
            </section>

            {/* 3. Nature of the Service */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">3. Nature of the Service</h2>
              <div className="mb-4 rounded-lg border border-blue-200 bg-blue-50 p-6">
                <p className="mb-2 font-semibold text-blue-900">
                  MarkM8 is an educational support tool—not an essay writing or ghostwriting service.
                </p>
              </div>
              <ul className="list-disc space-y-2 pl-6 text-slate-700">
                <li>Feedback and guidance provided are for educational and personal development only.</li>
                <li>All feedback, expected grades, and recommendations are generated by AI and/or other automated systems, which may not be entirely accurate or error-free.</li>
                <li>Our service is intended as supplementary guidance and should not replace your own academic efforts or human academic feedback.</li>
                <li>
                  MarkM8 does
                  {' '}
                  <strong>not</strong>
                  {' '}
                  guarantee any particular result, outcome, or grade.
                </li>
              </ul>
            </section>

            {/* 4. Permitted Use and Academic Integrity */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">4. Permitted Use and Academic Integrity</h2>

              <div className="mb-6 rounded-lg border border-red-200 bg-red-50 p-6">
                <h3 className="mb-3 text-xl font-semibold text-red-900">Prohibited Conduct:</h3>
                <p className="mb-3 text-slate-700">You agree not to:</p>
                <ul className="list-disc space-y-2 pl-6 text-slate-700">
                  <li>Submit, receive, or disseminate work intended for academic credit as your own original work without proper attribution (i.e., no plagiarism or academic misconduct).</li>
                  <li>Use the Platform to bypass or violate the academic integrity, honesty, or conduct policies of your institution.</li>
                  <li>Upload work that is not your own or attempt to use feedback as a substitute for genuine academic effort.</li>
                  <li>Use automated means to access, extract, or manipulate the Platform or disrupt its functionality.</li>
                  <li>Upload or distribute malicious code or content.</li>
                </ul>
              </div>

              <div className="mb-6 rounded-lg border border-amber-200 bg-amber-50 p-6">
                <h3 className="mb-3 text-xl font-semibold text-amber-900">Responsibility:</h3>
                <ul className="list-disc space-y-2 pl-6 text-slate-700">
                  <li>You are solely responsible for ensuring that your use of MarkM8 complies with the laws, regulations, and policies of your academic institution.</li>
                  <li>We do not monitor or verify your compliance with academic integrity policies, but we reserve the right to investigate and take appropriate action if violations are suspected.</li>
                </ul>
              </div>

              <div className="rounded-lg border border-red-300 bg-red-100 p-4">
                <h3 className="mb-2 text-xl font-semibold text-red-900">No Cheating or Plagiarism:</h3>
                <p className="text-red-800">
                  MarkM8 prohibits the use of its services for any form of academic dishonesty, including plagiarism, cheating, or using platform-generated content as your original work for academic credit.
                </p>
              </div>
            </section>

            {/* 5. User Content and Intellectual Property */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">5. User Content and Intellectual Property</h2>
              <ul className="list-disc space-y-2 pl-6 text-slate-700">
                <li>All content, feedback, and materials provided on the Platform are the property of MarkM8 or its licensors, protected by UK and international copyright laws.</li>
                <li>Users retain ownership of essays or content they upload but grant MarkM8 a non-exclusive, royalty-free license to use submitted materials (in anonymized and aggregated form) for research, platform improvement, and service delivery.</li>
                <li>You may not reproduce, distribute, modify, or create derivative works from our content without our express written consent.</li>
              </ul>
            </section>

            {/* 6. AI and Automated Feedback Disclaimer */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">6. AI and Automated Feedback Disclaimer</h2>
              <div className="rounded-lg border border-violet-200 bg-violet-50 p-6">
                <ul className="list-disc space-y-2 pl-6 text-slate-700">
                  <li>MarkM8 uses advanced AI and automated systems to generate feedback, grading, and recommendations.</li>
                  <li>While we strive for accuracy, we make no guarantee that the output is correct, error-free, or suitable for your academic requirements.</li>
                  <li>Users should not rely solely on MarkM8&apos;s feedback for any important academic decision and should exercise their own judgment or consult human educators when necessary.</li>
                </ul>
              </div>
            </section>

            {/* 7. User-Generated Content */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">7. User-Generated Content</h2>
              <ul className="list-disc space-y-2 pl-6 text-slate-700">
                <li>MarkM8 is not responsible for the accuracy, legality, or appropriateness of content submitted by users.</li>
                <li>Users must not upload content that is unlawful, defamatory, or infringes the rights of others.</li>
              </ul>
            </section>

            {/* 8. Payment, Credits, and Fees */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">8. Payment, Credits, and Fees</h2>
              <div className="rounded-lg border border-blue-200 bg-blue-50 p-6">
                <h3 className="mb-3 text-lg font-semibold text-blue-900">Pay-As-You-Go System</h3>
                <ul className="list-disc space-y-2 pl-6 text-slate-700">
                  <li>
                    <strong>Credits:</strong>
                    {' '}
                    Our Platform operates on a credit-based system. Credits are purchased in advance and used to access grading services.
                  </li>
                  <li>
                    <strong>Pricing:</strong>
                    {' '}
                    Grading costs are based on essay length, with transparent pricing displayed before submission.
                  </li>
                  <li>
                    <strong>Payment Processing:</strong>
                    {' '}
                    All payments are processed securely through Stripe. We do not store your payment card details.
                  </li>
                  <li>
                    <strong>Signup Bonus:</strong>
                    {' '}
                    New users receive a free credit upon account creation.
                  </li>
                  <li>
                    <strong>Minimum Purchase:</strong>
                    {' '}
                    Additional credits can be purchased with a minimum order of £5.00.
                  </li>
                  <li>
                    <strong>No Refunds:</strong>
                    {' '}
                    Credits are non-refundable once purchased, except in cases of technical failure or service unavailability.
                  </li>
                  <li>
                    <strong>Credit Expiry:</strong>
                    {' '}
                    Credits do not expire and remain available for future use.
                  </li>
                </ul>
              </div>
            </section>

            {/* 9. Privacy and Data Protection */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">9. Privacy and Data Protection</h2>
              <p className="mb-4 text-slate-700">
                Your privacy is important to us. Our
                {' '}
                <Link href="/privacy" className="text-violet-600 underline hover:text-violet-700">
                  Privacy Policy
                </Link>
                {' '}
                explains how we collect, use, and protect your information in compliance with the UK GDPR and Data Protection Act 2018.
              </p>
              <ul className="list-disc space-y-2 pl-6 text-slate-700">
                <li>We collect and process personal data only as necessary to provide our services.</li>
                <li>Essays and content you upload may be processed and stored securely, and used in anonymized, aggregated form to improve our platform and develop new features.</li>
                <li>You have rights regarding your personal data, as set out in our Privacy Policy.</li>
              </ul>
            </section>

            {/* 10. Changes to Service */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">10. Changes to Service</h2>
              <ul className="list-disc space-y-2 pl-6 text-slate-700">
                <li>We reserve the right to modify, suspend, or discontinue any aspect of the Platform at any time, including features, content, or availability.</li>
                <li>We may update these Terms periodically. We will notify users of significant changes where possible.</li>
                <li>Your continued use of the Platform after changes constitutes acceptance of the new Terms.</li>
              </ul>
            </section>

            {/* 11. Disclaimers and Limitation of Liability */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">11. Disclaimers and Limitation of Liability</h2>
              <div className="rounded-lg border border-slate-200 bg-slate-50 p-6">
                <ul className="list-disc space-y-2 pl-6 text-slate-700">
                  <li>MarkM8 provides services and information for general educational purposes only.</li>
                  <li>We do not guarantee any specific outcome, grade, or academic result from using our Platform.</li>
                  <li>MarkM8 and its affiliates, directors, employees, and agents are not liable for any disciplinary action, academic penalties, damages, losses, or claims arising from your use or misuse of the Platform, including acts of plagiarism, cheating, or other academic misconduct.</li>
                  <li>MarkM8 is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, express or implied.</li>
                  <li>Users are solely responsible for their use of the Platform and compliance with academic and legal requirements.</li>
                </ul>
              </div>
            </section>

            {/* 12. Institutional Use */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">12. Institutional Use</h2>
              <p className="text-slate-700">
                If you are using MarkM8 on behalf of an academic institution, or if your institution contracts with MarkM8, additional terms may apply. Please contact us for more information.
              </p>
            </section>

            {/* 13. Governing Law and Jurisdiction */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">13. Governing Law and Jurisdiction</h2>
              <p className="text-slate-700">
                These Terms are governed by and construed in accordance with the laws of England and Wales. Any disputes will be subject to the exclusive jurisdiction of the English courts.
              </p>
            </section>

            {/* 14. Contact */}
            <section className="mb-8">
              <h2 className="mb-4 text-2xl font-semibold text-slate-900">14. Contact</h2>
              <p className="mb-4 text-slate-700">
                If you have any questions or concerns about these Terms, please contact us at:
              </p>
              <p className="text-slate-700">
                <strong>Email:</strong>
                {' '}
                support@markm8.com
                <br />
                <strong>Address:</strong>
                {' '}
                London, United Kingdom
              </p>
            </section>

            {/* Key User Reminders */}
            <section className="mb-8">
              <div className="rounded-lg border border-yellow-200 bg-yellow-50 p-6">
                <h2 className="mb-4 text-xl font-semibold text-yellow-900">Key User Reminders:</h2>
                <ul className="list-disc space-y-2 pl-6 text-yellow-800">
                  <li>Don&apos;t use MarkM8 for plagiarism, cheating, or academic dishonesty.</li>
                  <li>We are not responsible for academic misconduct or related consequences.</li>
                  <li>Feedback is AI-generated guidance only, not a substitute for your own work or judgment.</li>
                  <li>UK law applies.</li>
                </ul>
              </div>
            </section>

            {/* Company Information */}
            <section className="mt-12 border-t border-slate-200 pt-8">
              <p className="text-center text-sm text-slate-600">
                <strong>MarkM8</strong>
                <br />
                London, United Kingdom
              </p>
            </section>
          </div>

          {/* Back to Home Button */}
          <div className="mt-12 text-center">
            <Link
              href="/"
              className="inline-flex items-center rounded-md border border-transparent bg-violet-600 px-6 py-3 text-base font-medium text-white transition-colors hover:bg-violet-700"
            >
              Back to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
